{% set python_min = "3.10" %}
{% set name = "pyflowdiagnostics" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7f6a54dd65fdf5fdcfa16cec03ea7772b6b8647e7a033fc4ece7fdd8e91412e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyflowdiagnostics = pyflowdiagnostics.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - h5py
    - pymatsolver
    - xlsxwriter
    - scooby

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pyflowdiagnostics
  commands:
    - pip check
    - pyflowdiagnostics --help

about:
  home: https://geg-ethz.github.io/pyflowdiagnostics/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Flow Diagnostics Toolkit
  description: |
    The Flow Diagnostics Toolkit `pyflowdiagnostics` provides a Python-based
    tool for flow diagnostics in reservoir simulation.

extra:
  recipe-maintainers:
    - prisae
    - Tsubasa-Onishi
